apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-param
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-param
  template:
    metadata:
     labels:
       app.kubernetes.io/name: secret-param
    spec:
      serviceAccountName: secret-param
      containers:
        - name: secret-param
          image: docker.io/cguimaraes/secret-param:latest
---
apiVersion: v1
kind: Service
metadata:
  name: secret-param
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secret-param
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-param
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-param-binding
subjects:
  - kind: ServiceAccount
    name: secret-param
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-secrets
  